# Generated by Django 3.2 on 2021-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='costumer_mobile',
            field=models.CharField(max_length=40),
        ),
    ]
